server:
 port: 8082
spring:
  application:
    name: upload-service
  servlet:
    multipart:
      max-file-size: 10MB # 限制文件上传的大小
# Eureka
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
fdfs:
 so-timeout: 1501
 connect-timeout: 601
 thumb-image: # 缩略图
  width: 60
  height: 60
 tracker-list: # tracker地址
 - 192.168.25.133:22122
 #属性读取
ly:
  upload:
    baseUrl: http://192.168.25.133/
    allowTypes:
      - image/png
      - image/jpg
      - image/jpeg
      - image/bmp